#pragma once

#define SDG_USE_OPENGL 1

#ifdef SDG_USE_VULKAN
	#undef SDG_USE_OPENGL
	define SDG_USE_VULKAN 1
#endif 

#ifdef SDG_DEBUG
	#define SDG_SHOWCONSOLE 1

	#define	SDG_ENABLE_TRACE_LOGGING 0

	#define SDG_GRAPHICS_API_INFO_LOGGING 0 // GL_DEBUG_SEVERITY_LOW | VK_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT
	#define SDG_GRAPHICS_API_VERBOSE_LOGGING 0 // GL_DEBUG_SEVERITY_NOTIFICATION | VK_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT
#elif SDG_RELEASE
	#define SDG_SHOWCONSOLE 1
#elif SDG_DIST
	
#endif